# -*- coding: utf-8 -*-
"""Books.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGl6bb5pVyY7QLRV-PTBI1O8s49ORyNc
"""

import pandas as pd
import requests as r
from bs4 import BeautifulSoup

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
webpage=r.get('https://books.toscrape.com/?page=1.html', headers=headers).text

soup= BeautifulSoup(webpage, 'lxml')

print(soup.prettify())

books=soup.find_all('li',class_='col-xs-6')

name=[]
rating=[]
price=[]
for i in books:
  name.append(i.find('h3').text)
  rating.append(i.find('p',class_='star-rating'))
  price.append(i.find('p',class_='price_color').text)

rating

rating_class = [r.get('class')[1] for r in rating]

d = {'Name': name, 'Rating': rating_class, 'Price': price}
df = pd.DataFrame(d)

df

final=pd.DataFrame()
for i in range(1,51):
  url='https://books.toscrape.com/catalogue/page-{}.html'.format(i)
  headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
  webpage=r.get(url, headers=headers).text
  soup= BeautifulSoup(webpage, 'lxml')
  books=soup.find_all('li',class_='col-xs-6')
  name=[]
  rating=[]
  price=[]
  for i in books:
    name.append(i.find('h3').text)
    rating.append(i.find('p',class_='star-rating'))
    price.append(i.find('p',class_='price_color').text)
    rating_class = [r.get('class')[1] for r in rating]

  d = {'Name': name, 'Rating': rating_class, 'Price': price}
  df = pd.DataFrame(d)
  final=pd.concat([final,df],ignore_index=True)

final

df.to_csv('books.csv')

